### ISSUE TITLE
Looking to get page numbers

### ISSUE THREAD

**Issue by eshaw29** [gerhardsletten/react-reader#50]
Trying to access the book underneath to render and get current page numbers as done here:

https://github.com/futurepress/epub.js/wiki/Tips-and-Tricks#generating-and-getting-page-numbers

Currently, I am using:

rendition.book.locations.generate(1024);
    rendition.on(
      'relocated',
      function(locations) {
        this.setState({
          currentPage: rendition.book.locations.locationFromCfi(locations.start.cfi).toString(),
          currentCfi: locations.start.cfi,
        });
      }.bind(this)
    );

to get the current page, but the values do not seem to be correct and they change depending on the size of the window. Is there a way that I can access the book object to use the functions provided in the link above?

**Comment by gerhardsletten** [comment]
Hi, @eshaw29 the page you refer to is for the v0.2 branch so this tip cant be used with the current used branch v0.3. There is a [tip-page for v3,](https://github.com/futurepress/epub.js/wiki/Tips-and-Tricks-%28v0.3%29) but I can't see anything about getting page-numbers there.

In general there are issues getting a correct number of pages for each chapter because its only for the current chapter you will now this exact page-number. For the other chapters I think you only can get the number of chars, but there could be images and other stuff and also just a paragraph of need to be rendered before its possible to inspect its dimension.

So would advice you to avoid this in a html-based epub reader..
