### ISSUE TITLE
Problem with big epub files it take alot of time to load

### ISSUE THREAD

**Issue by armanhadifatah** [gerhardsletten/react-reader#55]
Hi

Thanks for your great work , i'm using it in one of my app, one problem which i face when i have big epub file even if it is 8MB the loading time is around 10 second , i think it will load all 8MB and after that it show the page , isn't it better to load for example a part of epub not the whole so to take less time to show.

**Comment by gerhardsletten** [comment]
Hi @armanhadifatah 

Regular epub-files are zip-files packaged with the html-files and media files that is used in the epub, and I think with a pure client-side way of handling this, I think you would need to download the full epub-file before extracting its contents. This is also logic handled in the underlaying epubjs library.

So if you have many big epub-files I think a better way to handle this would be to parse the epub-file server-side, and send the toc and each chapter as html-content to the client. This way you would avoid loading the whole ebook before displaying it. But I am not sure if epubjs are able to just receive html-content directly in order to display the content.

Another solution would be to adjust and downsize media within the epub before delivering it to the user.
