### ISSUE TITLE
Audio support in epub file.

### ISSUE THREAD

**Issue by itopmoon** [gerhardsletten/react-reader#88]
Is it possible to play audio from the epub file? If not possible, is there any plan or way to add it?
Thanks.

**Comment by gerhardsletten** [comment]
@itopmoon See [limitations in readme](https://github.com/gerhardsletten/react-reader#limitations) on support for epub V3

**Comment by AjayManikantaG** [comment]
@itopmoon Just a heads up. In the current version, I was able to play audio based on smil file.

**Comment by gerhardsletten** [comment]
@AjayManikantaG Most likely its updates in epubjs

**Comment by AjayManikantaG** [comment]
@gerhardsletten I think we can remove some limitations that are described for react-reader. I was able to play animations and create read aloud functionality.

**Comment by gerhardsletten** [comment]
@AjayManikantaG Great to hear! In the [limitations in readme](https://github.com/gerhardsletten/react-reader#limitations) there is no special mention of audio support, and I also think it is out of scope to go into details about what Epub 3 features which is supported or not because this depends on [EpubJS](https://github.com/futurepress/epub.js/) which handles the rendering of the epub-file. But if they add some kind of supported features list, we can link to that.

> Just a heads up. In the current version, I was able to play audio based on smil file.

Was this working out the box, or did you need to add something in the config or rendering in react-reader? If so, feel free to share some sample code that could be added to the [recipes-and-tips section](https://github.com/gerhardsletten/react-reader#recipes-and-tips) in README.md
