### ISSUE TITLE
Suggestion: use onTouchTap instead of onClick

### ISSUE THREAD

**Issue by heymartinadams** [gerhardsletten/react-reader#9]
Changing `onClick` to `onTouchTap` in the `ReactReader.js` file using the [`react-tap-event-plugin`](https://github.com/zilverline/react-tap-event-plugin) removes the 300ms lag time when clicking left/right buttons for when ReactReader is used in Cordova 💯

**Comment by gerhardsletten** [comment]
Are you sure you still have this delay if you add the viewport / device-width metatag. Think it supported in most modern browsers today.

[From safari 9.1 release note](https://developer.apple.com/library/content/releasenotes/General/WhatsNewInSafari/Articles/Safari_9_1.html#//apple_ref/doc/uid/TP40014305-CH10-SW1)

> Fast-Tap on iOS
> On Safari for iOS, the 350 ms wait time to detect a second tap has been removed to create a “fast-tap” response. This is enabled for pages that declare a viewport with either width=device-width or user-scalable=no. Authors can also opt in to fast-tap behavior on specific elements by using the CSS touch-action property, using the manipulation value. See http://www.w3.org/TR/pointerevents/#the-touch-action-css-property.

[And chrome](https://developers.google.com/web/updates/2013/12/300ms-tap-delay-gone-away)

Not sure if its supportet in the native browser on Android though, but I think you will be able to apply  the FTLabs Fastclick on a react application as well, if you initialize it before you render the applications. Since epubjs and react-reader is not purely targeted at mobile devices it would be fine if we cound avoid device specific dependencies.

**Comment by heymartinadams** [comment]
Hi @gerhardsletten, yes I had added the viewport / device metatag and it was still giving me the lag. The lag disappeared when I either used the [`fastClick`](https://github.com/ftlabs/fastclick) library or the [`react-tap-event-plugin`](https://github.com/zilverline/react-tap-event-plugin).
